### ISSUE TITLE
IDEA: Simple LipSync

### ISSUE THREAD

**Issue by b4zz4** [tin2tin/volume_meter#1]
It seemed good to me to use this variable to encourage a simple lipsync. But the value is set in the reproduction and after passing through the frame.

Can it be generated before and during the render?

**Comment by tin2tin** [comment]
As mentioned, this is SNU's volumemeter from his VSEQF, but with a different UI. So, I only did the UI stuff and didn't look very closely on the internals. Feel free to improve on it. NB. the dev who did audaspace lib Blender uses, claims that this method is too imprecise, to be used.
